version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: todo-postgres
    restart: always
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - todo-net

volumes:
  postgres-data:

networks:
  todo-net:
